database:
  uri: "localhost/database"
  username: "homestead"
  password: "secret"

system:
  chat-prefix: "&l&b[BungeeClans]&r "
  clan-tag-length: 4 # Keep in mind, this tag is used in many command...not suggested to be above 4. It is case-sensitive
  join-request-til: 5 # In minutes, how long a join request from a clan owner to it's members will be valid.
  join-request-delay: 3 # In seconds, how long it takes before connecting the player to the clan owner's server.
  query-system: true # Allows querying of the plugin to return player info.
  query-port: 24565 # Change this if you have any conflicts
  server-aliases:
    - "hub-0": "Hub"
    - "skyblock": "Skyblock"

clan-defaults:
  name: "My BungeeClans Clan"
  description: "This is one awesome clan you should join!"
  motto: "Hack the planet!"
  max-members: 10 # Suggested to leave this to avoid huge clans.

web-panel:
  active: false
  override-commands: false # Makes commands like /bc create not work and go to web panel instead.
  base-url: "http://mysite.com/clans" # Base web application URL without trailing slash
  directory: "/directory" # List all clans
  clan-create: "/clan/create"
  clan-members: "/clan/{tag}/members"
  clan-info: "/clan/{tag}/info"

player:
  max-clans-joined: 1 # Max clans players can join by default.
  max-clans-owned: 1 # Max clans a player can own/create
  
  # Use bungeeclans.player.max-clans-(owned or joined).number to bypass max.
 
debug: false